# Generated by Django 3.1.1 on 2020-09-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('banner_image', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('banner_title', models.CharField(max_length=200)),
                ('banner_text', models.TextField()),
                ('button_text', models.CharField(max_length=20)),
                ('button_will_take_to', models.CharField(choices=[('about', 'About Section'), ('service', 'Service Section'), ('team', 'Team Section')], default='service', max_length=200)),
                ('feature_card_title', models.CharField(max_length=200)),
                ('feature_card_text', models.TextField()),
                ('about_image', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('about_title', models.CharField(max_length=200)),
                ('about_text', models.TextField()),
                ('service_title', models.CharField(max_length=200)),
                ('team_title', models.CharField(max_length=200)),
                ('team_text', models.TextField()),
                ('social_image_1', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('social_link_1', models.CharField(max_length=200)),
                ('social_image_2', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('social_link_2', models.CharField(max_length=200)),
                ('social_image_3', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('social_link_3', models.CharField(max_length=200)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
    ]
