# Generated by Django 3.1.1 on 2020-09-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_template', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('link', models.CharField(blank=True, help_text='For external links in menubar https://', max_length=20)),
                ('internal_link', models.CharField(blank=True, choices=[('about', 'About Section'), ('service', 'Service Section'), ('team', 'Team Section'), ('footer', 'Contact Us')], help_text='This will take you to a section of the page.Note that you should either give one of the link and not the both in same menu option', max_length=200)),
            ],
        ),
    ]
