# Generated by Django 3.1.1 on 2020-09-09 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_template', '0002_menu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
