# Generated by Django 3.1.1 on 2020-09-10 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_template', '0003_delete_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='button_will_take_to',
            field=models.CharField(choices=[('about', 'About Section'), ('services', 'Service Section'), ('team', 'Team Section'), ('footer', 'Contact us')], default='service', max_length=200),
        ),
    ]
