# Generated by Django 3.1.1 on 2020-09-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='internal_link',
            field=models.CharField(blank=True, choices=[('about', 'About Section'), ('service', 'Service Section'), ('team', 'Team Section'), ('footer', 'Contact Us')], help_text='This will take you to a section of the page.Note that you should either give one of the link and not the both in same menu option', max_length=200),
        ),
    ]
