# Generated by Django 3.1.1 on 2020-09-10 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20200909_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='link',
            new_name='external_link',
        ),
        migrations.AddField(
            model_name='menu',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
